version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: "${MYSQL_ROOT_PASSWORD}"
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"